config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :topics do
    resources :messages
  end
  root "topics#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :topic
  broadcasts_to :topic
  
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :messages, dependent: :destroy
    belongs_to :user
    broadcasts
    validates :title, presence: true
    validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

    before_action :configure_permitted_parameters, if: :devise_controller?
    

    def after_sign_in_path_for(users)
        topics_path
    end
    def after_sign_out_path_for(users)
        root_path
    end

    protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password)}

               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :password, :current_password)}
          end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_topic, only: %i[new create]

    def new
        @message = @topic.messages.new
    end

    def create
        @message = @topic.messages.create!(message_params)

        respond_to do |format|
            format.turbo_stream
            format.html { redirect_to @topic}
        end
    end

    private
        def set_topic
            @topic = Topic.find(params[:topic_id])
        end

        def message_params
            params.require(:message).permit(:content)
        end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: %i[ show edit update destroy ]

  # GET /topics or /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1 or /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics or /topics.json
  def create
    @topic = current_user.topics.build(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully created." }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1 or /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to topic_url(@topic), notice: "Topic was successfully updated." }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1 or /topics/1.json
  def destroy
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url, notice: "Topic was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_flash_messages.html.erb
<div class="text-center my-2">
    <% if notice %>
        <div class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></div>
    <% end %>
    <% if alert %>
        <div class="py-2 px-3 bg-orange-50 mb-5 text-orange-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="flex flex-wrap items-center bg-cyan-500 text-white justify-between w-full
relative py-5 h-16   md:py-0 px-5
          text-lg">
  <div>
    <%= link_to "Topical", root_path, 
    class: "text-2xl font-extrabold antialiased  hover:underline"%>
  </div>
 
  <div>
    <%= link_to "Home", root_path, class: "font-semibold antialiased  hover:underline"%>
    <%= link_to "Topics", topics_path, class: "font-semibold antialiased  hover:underline"%>
  </div>
  <div class="hidden w-full md:flex md:items-center md:justify-between md:w-auto " id="menu">
    <ul class="text-base pt-4 md:flex md:justify-between md:pt-0 space-x-3">
      <% if user_signed_in? %>
         <li><%= link_to "Profile", edit_user_registration_path, class: "font-semibold antialiased text-white hover:underline" %></li>
      <li class="font-semibold antialiased text-white "> Welcome <%= current_user.username %> </li> 
        <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "font-semibold font-sans antialiased  hover:underline" %> 
      
        
        </li>
       
      <% else %>
      <li><%= link_to "Sign in", new_user_session_path, class: "font-semibold font-sans hover:underline antialiased " %></li> 
      <li><%= link_to "Sign up", new_user_registration_path, class: "font-semibold font-sans hover:underline antialiased " %></li> 
      <% end %>
    
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Topical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= render "layouts/navbar" %>
      <%= render "layouts/flash_messages" %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<p id="<%= dom_id message %>">
    <%= message.content %> <br/ > <%= message.created_at.to_s(:short) %> 
</p>

app/views/messages/new.html.erb
<div class="mx-auto w-1/3">
    <h1 class="bg-gray-100 p-3 text-center">New Comment</h1>

    <%= turbo_frame_tag "new_message", target: "_top" do %>
    
        <%= form_with(model: [ @message.topic, @message ],
         data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" }) do |form| %>

            
            <div class="my-5">
                <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
            </div>
            <div class="">
                <%= form.submit "Comment", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer w-48" %>
                
            </div>
        <% end %>
    <% end %>

</div>

app/views/topics/_form.html.erb
<%= form_with(model: topic, class: "contents") do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% topic.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= topic.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= topic.content %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this topic", topic, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    
    <% if user_signed_in? %>
      <%= link_to 'Edit this topic', edit_topic_path(topic), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/topics/edit.html.erb
<div class="mx-auto md:w-2/3 w-1/2">
  <h1 class="font-bold text-4xl">Editing topic</h1>
  <%= turbo_frame_tag "topic" do %>
    <%= render "form", topic: @topic %>
  <% end %>

  <%= link_to "Show this topic", @topic, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to topics", topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/topics/index.html.erb
<div class=" mx-auto w-1/2">
  

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl bg-slate-200 max-w-lg p-2 text-center rounded">Topics</h1>
    <% if user_signed_in? %>
      <%= link_to 'New topic', new_topic_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    <% end %>
  </div>

  <div id="topics" class="max-w-full">
    <%= render @topics %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New topic</h1>

  <%= render "form", topic: @topic %>

  <%= link_to 'Back to topics', topics_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/topics/show.html.erb
<div class="mx-auto md:w-2/3 w-1/3 flex">
  <div class="mx-auto">
    

    <%= turbo_stream_from @topic %>
    <%= turbo_frame_tag "topic" do %>
      <%= render @topic %>

      <% if user_signed_in? %>
        <%= link_to 'Edit this topic', edit_topic_path(@topic), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-2">
          <%= link_to 'Destroy this topic', topic_path(@topic),
          data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
        </div>
      <% end %>
    <% end %>
      <%= link_to 'Back to topics', topics_path, "data-turbo-frame": "_top", class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    
    <div class="mx-auto py-8 space-y-8">
    <h1 class="bg-gray-100 p-3 text-center">Comments</h1>
      <div id="messages">
        <%= render @topic.messages %>
      </div>
    <% if user_signed_in? %>
      <div>
        <%= turbo_frame_tag "new_message", src: new_topic_message_path(@topic),
         target: "_top" %>
      </div>
    <% end %>
    </div>

  </div>

</div>